# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!

import resources
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1002, 872)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1000, 873))
        self.stackedWidget.setObjectName("stackedWidget")
        self.loginPage = QtWidgets.QWidget()
        self.loginPage.setStyleSheet("border-image: url(:/Images/Resources/signInBG.png);")
        self.loginPage.setObjectName("loginPage")
        self.button_signIn_signIn = QtWidgets.QPushButton(self.loginPage)
        self.button_signIn_signIn.setGeometry(QtCore.QRect(320, 590, 320, 45))
        self.button_signIn_signIn.setStyleSheet("border-image: url(:/Images/Resources/signIn.png);")
        self.button_signIn_signIn.setText("")
        self.button_signIn_signIn.setObjectName("button_signIn_signIn")
        self.button_faceID_signIn = QtWidgets.QPushButton(self.loginPage)
        self.button_faceID_signIn.setGeometry(QtCore.QRect(320, 660, 320, 45))
        self.button_faceID_signIn.setStyleSheet("border-image: url(:/Images/Resources/faceID.png);\n"
"")
        self.button_faceID_signIn.setText("")
        self.button_faceID_signIn.setObjectName("button_faceID_signIn")
        self.button_signUp_signIn = QtWidgets.QPushButton(self.loginPage)
        self.button_signUp_signIn.setGeometry(QtCore.QRect(320, 730, 320, 45))
        self.button_signUp_signIn.setStyleSheet("border-image: url(:/Images/Resources/signUp.png);")
        self.button_signUp_signIn.setText("")
        self.button_signUp_signIn.setObjectName("button_signUp_signIn")
        self.lineEdit_username_signIn = QtWidgets.QLineEdit(self.loginPage)
        self.lineEdit_username_signIn.setGeometry(QtCore.QRect(300, 351, 381, 31))
        self.lineEdit_username_signIn.setStyleSheet("border-image: url(:/Images/Resources/darkBlackBG.png);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_username_signIn.setObjectName("lineEdit_username_signIn")
        self.lineEdit_password_signIn = QtWidgets.QLineEdit(self.loginPage)
        self.lineEdit_password_signIn.setGeometry(QtCore.QRect(300, 421, 381, 41))
        self.lineEdit_password_signIn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.lineEdit_password_signIn.setStyleSheet("border-image: url(:/Images/Resources/darkBlackBG.png);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_password_signIn.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password_signIn.setObjectName("lineEdit_password_signIn")
        self.stackedWidget.addWidget(self.loginPage)
        self.signupPage = QtWidgets.QWidget()
        self.signupPage.setStyleSheet("border-image: url(:/Images/Resources/signUpBG.png);")
        self.signupPage.setObjectName("signupPage")
        self.lineEdit_firstName_signUp = QtWidgets.QLineEdit(self.signupPage)
        self.lineEdit_firstName_signUp.setGeometry(QtCore.QRect(300, 330, 151, 29))
        self.lineEdit_firstName_signUp.setStyleSheet("border-image: url(:/Images/Resources/darkBlackBG.png);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_firstName_signUp.setObjectName("lineEdit_firstName_signUp")
        self.lineEdit_lastName_signUp = QtWidgets.QLineEdit(self.signupPage)
        self.lineEdit_lastName_signUp.setGeometry(QtCore.QRect(520, 330, 151, 29))
        self.lineEdit_lastName_signUp.setStyleSheet("border-image: url(:/Images/Resources/darkBlackBG.png);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_lastName_signUp.setObjectName("lineEdit_lastName_signUp")
        self.lineEdit_email_signUp = QtWidgets.QLineEdit(self.signupPage)
        self.lineEdit_email_signUp.setGeometry(QtCore.QRect(300, 400, 371, 21))
        self.lineEdit_email_signUp.setStyleSheet("border-image: url(:/Images/Resources/darkBlackBG.png);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_email_signUp.setObjectName("lineEdit_email_signUp")
        self.lineEdit_username_signUp = QtWidgets.QLineEdit(self.signupPage)
        self.lineEdit_username_signUp.setGeometry(QtCore.QRect(300, 480, 371, 21))
        self.lineEdit_username_signUp.setStyleSheet("border-image: url(:/Images/Resources/darkBlackBG.png);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_username_signUp.setObjectName("lineEdit_username_signUp")
        self.lineEdit_password_signUp = QtWidgets.QLineEdit(self.signupPage)
        self.lineEdit_password_signUp.setGeometry(QtCore.QRect(300, 560, 371, 21))
        self.lineEdit_password_signUp.setStyleSheet("\n"
"border-image: url(:/Images/Resources/darkBlackBG.png);\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_password_signUp.setObjectName("lineEdit_password_signUp")
        self.button_signUp_signUp = QtWidgets.QPushButton(self.signupPage)
        self.button_signUp_signUp.setGeometry(QtCore.QRect(340, 640, 320, 45))
        self.button_signUp_signUp.setStyleSheet("border-image: url(:/Images/Resources/signUp.png);")
        self.button_signUp_signUp.setText("")
        self.button_signUp_signUp.setObjectName("button_signUp_signUp")
        self.button_backToSignIn = QtWidgets.QPushButton(self.signupPage)
        self.button_backToSignIn.setGeometry(QtCore.QRect(340, 720, 320, 45))
        self.button_backToSignIn.setStyleSheet("border-image: url(:/Images/Resources/backSignInPressed.png);")
        self.button_backToSignIn.setText("")
        self.button_backToSignIn.setObjectName("button_backToSignIn")
        self.stackedWidget.addWidget(self.signupPage)
        self.faceidPage = QtWidgets.QWidget()
        self.faceidPage.setStyleSheet("border-image: url(:/Images/Resources/faceIDWidget.png);")
        self.faceidPage.setObjectName("faceidPage")
        self.label_cam = QtWidgets.QLabel(self.faceidPage)
        self.label_cam.setGeometry(QtCore.QRect(90, 230, 821, 401))
        self.label_cam.setStyleSheet("border-image: url(:/Images/Resources/semiDarkBG.png);")
        self.label_cam.setText("")
        self.label_cam.setObjectName("label_cam")
        self.stackedWidget.addWidget(self.faceidPage)
        self.mainPage = QtWidgets.QWidget()
        self.mainPage.setStyleSheet("border-image: url(:/Images/Resources/mainWidgetBG.png);")
        self.mainPage.setObjectName("mainPage")
        self.button_dashboard = QtWidgets.QPushButton(self.mainPage)
        self.button_dashboard.setGeometry(QtCore.QRect(0, 200, 291, 54))
        self.button_dashboard.setStyleSheet("border-image: url(:/Images/Resources/dasboard.png);")
        self.button_dashboard.setText("")
        self.button_dashboard.setObjectName("button_dashboard")
        self.button_createTank = QtWidgets.QPushButton(self.mainPage)
        self.button_createTank.setGeometry(QtCore.QRect(0, 280, 291, 54))
        self.button_createTank.setStyleSheet("border-image: url(:/Images/Resources/create.png);")
        self.button_createTank.setText("")
        self.button_createTank.setObjectName("button_createTank")
        self.button_analyzeTank = QtWidgets.QPushButton(self.mainPage)
        self.button_analyzeTank.setGeometry(QtCore.QRect(0, 350, 291, 54))
        self.button_analyzeTank.setStyleSheet("border-image: url(:/Images/Resources/analyze.png);")
        self.button_analyzeTank.setText("")
        self.button_analyzeTank.setObjectName("button_analyzeTank")
        self.button_settings = QtWidgets.QPushButton(self.mainPage)
        self.button_settings.setGeometry(QtCore.QRect(0, 420, 291, 54))
        self.button_settings.setStyleSheet("border-image: url(:/Images/Resources/settings.png);")
        self.button_settings.setText("")
        self.button_settings.setObjectName("button_settings")
        self.button_logout = QtWidgets.QPushButton(self.mainPage)
        self.button_logout.setGeometry(QtCore.QRect(70, 680, 130, 42))
        self.button_logout.setStyleSheet("border-image: url(:/Images/Resources/logoutPressed.png);")
        self.button_logout.setText("")
        self.button_logout.setObjectName("button_logout")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.mainPage)
        self.stackedWidget_2.setGeometry(QtCore.QRect(290, 0, 711, 861))
        self.stackedWidget_2.setStyleSheet("border-image: url(:/Images/Resources/CreateBG.png);")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.dashboardPage = QtWidgets.QWidget()
        self.dashboardPage.setStyleSheet("border-image: url(:/Images/Resources/dashboardWidget.png);")
        self.dashboardPage.setObjectName("dashboardPage")
        self.label_fishType_tankData = QtWidgets.QLabel(self.dashboardPage)
        self.label_fishType_tankData.setGeometry(QtCore.QRect(170, 180, 55, 16))
        self.label_fishType_tankData.setStyleSheet("border-image: url(:/Images/Resources/whiteBG.png);")
        self.label_fishType_tankData.setObjectName("label_fishType_tankData")
        self.label_harvestDate_tankData = QtWidgets.QLabel(self.dashboardPage)
        self.label_harvestDate_tankData.setGeometry(QtCore.QRect(200, 230, 71, 16))
        self.label_harvestDate_tankData.setStyleSheet("border-image: url(:/Images/Resources/whiteBG.png);")
        self.label_harvestDate_tankData.setObjectName("label_harvestDate_tankData")
        self.label_feeding_tankData = QtWidgets.QLabel(self.dashboardPage)
        self.label_feeding_tankData.setGeometry(QtCore.QRect(240, 280, 71, 16))
        self.label_feeding_tankData.setStyleSheet("border-image: url(:/Images/Resources/whiteBG.png);")
        self.label_feeding_tankData.setObjectName("label_feeding_tankData")
        self.label_ph_tankData = QtWidgets.QLabel(self.dashboardPage)
        self.label_ph_tankData.setGeometry(QtCore.QRect(120, 320, 55, 16))
        self.label_ph_tankData.setStyleSheet("border-image: url(:/Images/Resources/whiteBG.png);")
        self.label_ph_tankData.setObjectName("label_ph_tankData")
        self.label_temperature_tankData = QtWidgets.QLabel(self.dashboardPage)
        self.label_temperature_tankData.setGeometry(QtCore.QRect(200, 370, 55, 16))
        self.label_temperature_tankData.setStyleSheet("border-image: url(:/Images/Resources/whiteBG.png);")
        self.label_temperature_tankData.setObjectName("label_temperature_tankData")
        self.label_fishNetHoles_tankData = QtWidgets.QLabel(self.dashboardPage)
        self.label_fishNetHoles_tankData.setGeometry(QtCore.QRect(210, 420, 55, 16))
        self.label_fishNetHoles_tankData.setStyleSheet("border-image: url(:/Images/Resources/whiteBG.png);")
        self.label_fishNetHoles_tankData.setObjectName("label_fishNetHoles_tankData")
        self.label_fishnetNeedsCleaning_tankData = QtWidgets.QLabel(self.dashboardPage)
        self.label_fishnetNeedsCleaning_tankData.setGeometry(QtCore.QRect(280, 470, 55, 16))
        self.label_fishnetNeedsCleaning_tankData.setStyleSheet("border-image: url(:/Images/Resources/whiteBG.png);")
        self.label_fishnetNeedsCleaning_tankData.setObjectName("label_fishnetNeedsCleaning_tankData")
        self.label_pipesNeedChanging_tankData = QtWidgets.QLabel(self.dashboardPage)
        self.label_pipesNeedChanging_tankData.setGeometry(QtCore.QRect(262, 513, 55, 16))
        self.label_pipesNeedChanging_tankData.setStyleSheet("border-image: url(:/Images/Resources/whiteBG.png);")
        self.label_pipesNeedChanging_tankData.setObjectName("label_pipesNeedChanging_tankData")
        self.comboBox = QtWidgets.QComboBox(self.dashboardPage)
        self.comboBox.setGeometry(QtCore.QRect(280, 30, 73, 22))
        self.comboBox.setStyleSheet("border-image: url(:/Images/Resources/comboBoxBG.png);\n"
"\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.stackedWidget_2.addWidget(self.dashboardPage)
        self.createtankPage = QtWidgets.QWidget()
        self.createtankPage.setObjectName("createtankPage")
        self.lineEdit_fishType_createTank = QtWidgets.QLineEdit(self.createtankPage)
        self.lineEdit_fishType_createTank.setGeometry(QtCore.QRect(410, 452, 171, 22))
        self.lineEdit_fishType_createTank.setStyleSheet("border-image: url(:/Images/Resources/darkBlackBG.png);")
        self.lineEdit_fishType_createTank.setObjectName("lineEdit_fishType_createTank")
        self.lineEdit_date_createTank = QtWidgets.QLineEdit(self.createtankPage)
        self.lineEdit_date_createTank.setGeometry(QtCore.QRect(410, 498, 171, 22))
        self.lineEdit_date_createTank.setStyleSheet("border-image: url(:/Images/Resources/darkBlackBG.png);")
        self.lineEdit_date_createTank.setObjectName("lineEdit_date_createTank")
        self.lineEdit_feeding_createTank = QtWidgets.QLineEdit(self.createtankPage)
        self.lineEdit_feeding_createTank.setGeometry(QtCore.QRect(412, 540, 171, 22))
        self.lineEdit_feeding_createTank.setStyleSheet("border-image: url(:/Images/Resources/darkBlackBG.png);")
        self.lineEdit_feeding_createTank.setObjectName("lineEdit_feeding_createTank")
        self.lineEdit_lowerTemperatureThreshold_createTank = QtWidgets.QLineEdit(self.createtankPage)
        self.lineEdit_lowerTemperatureThreshold_createTank.setGeometry(QtCore.QRect(410, 590, 161, 22))
        self.lineEdit_lowerTemperatureThreshold_createTank.setStyleSheet("border-image: url(:/Images/Resources/darkBlackBG.png);")
        self.lineEdit_lowerTemperatureThreshold_createTank.setObjectName("lineEdit_lowerTemperatureThreshold_createTank")
        self.lineEdit_upperTemperatureThreshold_createTank = QtWidgets.QLineEdit(self.createtankPage)
        self.lineEdit_upperTemperatureThreshold_createTank.setGeometry(QtCore.QRect(420, 632, 161, 22))
        self.lineEdit_upperTemperatureThreshold_createTank.setStyleSheet("border-image: url(:/Images/Resources/darkBlackBG.png);")
        self.lineEdit_upperTemperatureThreshold_createTank.setObjectName("lineEdit_upperTemperatureThreshold_createTank")
        self.lineEdit_waterQualityThreshold_createTank = QtWidgets.QLineEdit(self.createtankPage)
        self.lineEdit_waterQualityThreshold_createTank.setGeometry(QtCore.QRect(410, 680, 161, 22))
        self.lineEdit_waterQualityThreshold_createTank.setStyleSheet("border-image: url(:/Images/Resources/darkBlackBG.png);")
        self.lineEdit_waterQualityThreshold_createTank.setObjectName("lineEdit_waterQualityThreshold_createTank")
        self.stackedWidget_2.addWidget(self.createtankPage)
        self.analyzetankPage = QtWidgets.QWidget()
        self.analyzetankPage.setStyleSheet("border-image: url(:/Images/Resources/AnalyzeBG.png);")
        self.analyzetankPage.setObjectName("analyzetankPage")
        self.button_holes_analyzeTank = QtWidgets.QPushButton(self.analyzetankPage)
        self.button_holes_analyzeTank.setGeometry(QtCore.QRect(110, 510, 127, 33))
        self.button_holes_analyzeTank.setStyleSheet("border-image: url(:/Images/Resources/Holes.png);")
        self.button_holes_analyzeTank.setText("")
        self.button_holes_analyzeTank.setObjectName("button_holes_analyzeTank")
        self.button_cleaning_analyzeTank = QtWidgets.QPushButton(self.analyzetankPage)
        self.button_cleaning_analyzeTank.setGeometry(QtCore.QRect(280, 510, 127, 33))
        self.button_cleaning_analyzeTank.setStyleSheet("border-image: url(:/Images/Resources/Cleaning.png);")
        self.button_cleaning_analyzeTank.setText("")
        self.button_cleaning_analyzeTank.setObjectName("button_cleaning_analyzeTank")
        self.button_pipes_analyzeTank = QtWidgets.QPushButton(self.analyzetankPage)
        self.button_pipes_analyzeTank.setGeometry(QtCore.QRect(440, 510, 127, 33))
        self.button_pipes_analyzeTank.setStyleSheet("border-image: url(:/Images/Resources/Pipes.png);")
        self.button_pipes_analyzeTank.setText("")
        self.button_pipes_analyzeTank.setObjectName("button_pipes_analyzeTank")
        self.button_predict_analyzeTank = QtWidgets.QPushButton(self.analyzetankPage)
        self.button_predict_analyzeTank.setGeometry(QtCore.QRect(440, 590, 127, 33))
        self.button_predict_analyzeTank.setStyleSheet("border-image: url(:/Images/Resources/predict.png);")
        self.button_predict_analyzeTank.setText("")
        self.button_predict_analyzeTank.setObjectName("button_predict_analyzeTank")
        self.label_fishnetNeedsPatching_analyzeTank = QtWidgets.QLabel(self.analyzetankPage)
        self.label_fishnetNeedsPatching_analyzeTank.setGeometry(QtCore.QRect(280, 563, 55, 16))
        self.label_fishnetNeedsPatching_analyzeTank.setStyleSheet("border-image: url(:/Images/Resources/whiteBG.png);")
        self.label_fishnetNeedsPatching_analyzeTank.setObjectName("label_fishnetNeedsPatching_analyzeTank")
        self.label_fishnetNeedsCleaning_analyzeTank = QtWidgets.QLabel(self.analyzetankPage)
        self.label_fishnetNeedsCleaning_analyzeTank.setGeometry(QtCore.QRect(280, 603, 55, 16))
        self.label_fishnetNeedsCleaning_analyzeTank.setStyleSheet("border-image: url(:/Images/Resources/whiteBG.png);")
        self.label_fishnetNeedsCleaning_analyzeTank.setObjectName("label_fishnetNeedsCleaning_analyzeTank")
        self.label_pipesNeedChanging_analyzeTank = QtWidgets.QLabel(self.analyzetankPage)
        self.label_pipesNeedChanging_analyzeTank.setGeometry(QtCore.QRect(260, 650, 55, 16))
        self.label_pipesNeedChanging_analyzeTank.setStyleSheet("border-image: url(:/Images/Resources/whiteBG.png);")
        self.label_pipesNeedChanging_analyzeTank.setObjectName("label_pipesNeedChanging_analyzeTank")
        self.lineEdit_temperature_analyzeTank = QtWidgets.QLineEdit(self.analyzetankPage)
        self.lineEdit_temperature_analyzeTank.setGeometry(QtCore.QRect(550, 560, 113, 22))
        self.lineEdit_temperature_analyzeTank.setStyleSheet("border-image: url(:/Images/Resources/whiteBG.png);")
        self.lineEdit_temperature_analyzeTank.setObjectName("lineEdit_temperature_analyzeTank")
        self.lineEdit_waterSalinity_analyzeTank = QtWidgets.QLineEdit(self.analyzetankPage)
        self.lineEdit_waterSalinity_analyzeTank.setGeometry(QtCore.QRect(550, 650, 113, 22))
        self.lineEdit_waterSalinity_analyzeTank.setStyleSheet("border-image: url(:/Images/Resources/whiteBG.png);")
        self.lineEdit_waterSalinity_analyzeTank.setObjectName("lineEdit_waterSalinity_analyzeTank")
        self.stackedWidget_2.addWidget(self.analyzetankPage)
        self.settingsPage = QtWidgets.QWidget()
        self.settingsPage.setStyleSheet("border-image: url(:/Images/Resources/settingsWidget.png);")
        self.settingsPage.setObjectName("settingsPage")
        self.stackedWidget_2.addWidget(self.settingsPage)
        self.label_username_mainPage = QtWidgets.QLabel(self.mainPage)
        self.label_username_mainPage.setGeometry(QtCore.QRect(120, 140, 101, 16))
        self.label_username_mainPage.setStyleSheet("border-image: url(:/Images/Resources/blueBG.png);")
        self.label_username_mainPage.setObjectName("label_username_mainPage")
        self.label_user_admin = QtWidgets.QLabel(self.mainPage)
        self.label_user_admin.setGeometry(QtCore.QRect(140, 170, 101, 16))
        self.label_user_admin.setStyleSheet("border-image: url(:/Images/Resources/blueBG.png);")
        self.label_user_admin.setObjectName("label_user_admin")
        self.label_userLetter = QtWidgets.QLabel(self.mainPage)
        self.label_userLetter.setGeometry(QtCore.QRect(50, 140, 31, 31))
        self.label_userLetter.setStyleSheet("border-image: url(:/Images/Resources/greyBG.png);\n"
"font: 26pt \"MS Shell Dlg 2\";")
        self.label_userLetter.setObjectName("label_userLetter")
        self.stackedWidget.addWidget(self.mainPage)
        MainWindow.setCentralWidget(self.centralwidget)

        self.buttonsConnections()

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_username_signIn.setText(_translate("MainWindow", "Username"))
        self.lineEdit_password_signIn.setText(_translate("MainWindow", "12345678"))
        self.lineEdit_firstName_signUp.setText(_translate("MainWindow", "First name"))
        self.lineEdit_lastName_signUp.setText(_translate("MainWindow", "Last name"))
        self.lineEdit_email_signUp.setText(_translate("MainWindow", "Email address"))
        self.lineEdit_username_signUp.setText(_translate("MainWindow", "Username"))
        self.lineEdit_password_signUp.setText(_translate("MainWindow", "Password"))
        self.label_fishType_tankData.setText(_translate("MainWindow", "Salmon"))
        self.label_harvestDate_tankData.setText(_translate("MainWindow", "29/7/2019"))
        self.label_feeding_tankData.setText(_translate("MainWindow", "6:00:00"))
        self.label_ph_tankData.setText(_translate("MainWindow", "6.2"))
        self.label_temperature_tankData.setText(_translate("MainWindow", "22"))
        self.label_fishNetHoles_tankData.setText(_translate("MainWindow", "1"))
        self.label_fishnetNeedsCleaning_tankData.setText(_translate("MainWindow", "No"))
        self.label_pipesNeedChanging_tankData.setText(_translate("MainWindow", "No"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Tank 1"))
        self.label_fishnetNeedsPatching_analyzeTank.setText(_translate("MainWindow", "No"))
        self.label_fishnetNeedsCleaning_analyzeTank.setText(_translate("MainWindow", "No"))
        self.label_pipesNeedChanging_analyzeTank.setText(_translate("MainWindow", "No"))
        self.label_username_mainPage.setText(_translate("MainWindow", "Abdullah Salah"))
        self.label_user_admin.setText(_translate("MainWindow", "user"))
        self.label_userLetter.setText(_translate("MainWindow", "A"))



    def signInIsClicked(self):
        username_signIn = self.lineEdit_username_signIn.text()
        password_signIn = self.lineEdit_password_signIn.text()
        self.stackedWidget.setCurrentIndex(3)

        

    def signUpfromLoginPageIsClicked(self):
        self.stackedWidget.setCurrentIndex(1)

    def signUpfromsignUpPageIsClicked(self):
        self.stackedWidget.setCurrentIndex(0)
        username_signUp=self.lineEdit_username_signUp.text()
        password_signUp=self.lineEdit_password_signUp.text()
        firstName_signUp=self.lineEdit_firstName_signUp.text()
        lastName_signUp=self.lineEdit_lastName_signUp.text()
        email_signUp=self.lineEdit_email_signUp.text()

        
    def faceIdIsClicked(self):
        self.stackedWidget.setCurrentIndex(2)

    def goToLoginPage(self):
        self.stackedWidget.setCurrentIndex(0)

    def dashboardIsClicked(self):
        self.stackedWidget_2.setCurrentIndex(0)

    def createTankIsClicked(self):
        self.stackedWidget_2.setCurrentIndex(1)
        fishType_createTank= self.lineEdit_fishType_createTank.text()
        date_createTank= self.lineEdit_date_createTank.text()
        feeding_createTank= self.lineEdit_feeding_createTank.text()
        lowerTemperatureThreshold_createTank= self.lineEdit_lowerTemperatureThreshold_createTank.text()
        upperTemperatureThreshold_createTank= self.lineEdit_upperTemperatureThreshold_createTank.text()
        waterQualityThreshold_createTank= self.lineEdit_waterQualityThreshold_createTank.text()

        
    def analyzeTankIsClicked(self):
        self.stackedWidget_2.setCurrentIndex(2)

    def settingsIsClicked(self):
        self.stackedWidget_2.setCurrentIndex(3)

    def cleaningIsClicked(self):
        pass
    
    def holesIsClicked(self):
        pass

    def pipesIsClicked(self):
        pass

    def predictIsClicked(self):
        pass
    
    def buttonsConnections(self):
        self.button_signIn_signIn.clicked.connect(self.signInIsClicked)
        self.button_signUp_signIn.clicked.connect(self.signUpfromLoginPageIsClicked)
        self.button_faceID_signIn.clicked.connect(self.faceIdIsClicked)
        self.button_backToSignIn.clicked.connect(self.goToLoginPage)
        self.button_signUp_signUp.clicked.connect(self.signUpfromsignUpPageIsClicked)
        self.button_logout.clicked.connect(self.goToLoginPage)
        self.button_dashboard.clicked.connect(self.dashboardIsClicked)
        self.button_createTank.clicked.connect(self.createTankIsClicked)
        self.button_analyzeTank.clicked.connect(self.analyzeTankIsClicked)
        self.button_settings.clicked.connect(self.settingsIsClicked)
        self.button_cleaning_analyzeTank.clicked.connect(self.cleaningIsClicked)
        self.button_holes_analyzeTank.clicked.connect(self.holesIsClicked)
        self.button_pipes_analyzeTank.clicked.connect(self.pipesIsClicked)
        self.button_predict_analyzeTank.clicked.connect(self.predictIsClicked)
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
